# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: container_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'container_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ontainer_data.proto\x12\tcontainer\"\xee\x02\n\rContainerData\x12\x0e\n\x06msisdn\x18\x01 \x01(\t\x12\x0f\n\x07iso6346\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x0b\n\x03\x63gi\x18\x04 \x01(\t\x12\x0c\n\x04\x64oor\x18\x05 \x01(\t\x12\x0c\n\x04rssi\x18\x06 \x01(\r\x12\r\n\x05\x62le_m\x18\x07 \x01(\r\x12\x0f\n\x07\x62\x61t_soc\x18\x08 \x01(\r\x12\x0c\n\x04gnss\x18\t \x01(\r\x12\x0c\n\x04nsat\x18\n \x01(\r\x12\r\n\x05\x61\x63\x63_x\x18\x0b \x01(\x02\x12\r\n\x05\x61\x63\x63_y\x18\x0c \x01(\x02\x12\r\n\x05\x61\x63\x63_z\x18\r \x01(\x02\x12\x13\n\x0btemperature\x18\x0e \x01(\x02\x12\x10\n\x08humidity\x18\x0f \x01(\x02\x12\x10\n\x08pressure\x18\x10 \x01(\x02\x12\x10\n\x08latitude\x18\x11 \x01(\x02\x12\x11\n\tlongitude\x18\x12 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x13 \x01(\x02\x12\r\n\x05speed\x18\x14 \x01(\x02\x12\x0f\n\x07heading\x18\x15 \x01(\x02\x12\x0c\n\x04hdop\x18\x16 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'container_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTAINERDATA']._serialized_start=36
  _globals['_CONTAINERDATA']._serialized_end=402
# @@protoc_insertion_point(module_scope)
